server:
  port: 8082

security: 
    user: 
        name: qinjee
        password: qinjee2019

spring:
  application:
    name: qinjee-feign
    
eureka: 
  instance:
    instance-id: qinjee-feign-${server.port}
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8888/eureka/
#      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8888/eureka/,http://${security.user.name}:${security.user.password}@localhost:8889/eureka/