server:
  port: 5555

spring: 
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 0
    
zuul: 
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
#  sensitiveHeaders的默认值初始值是"Cookie", "Set-Cookie", "Authorization"这三项，不设置为空会导致无法设置cookie
  sensitive-headers: 
  prefix: /api
  routes: 
    qinjee-tsc: 
      path: /tsc/**
      serviceId: qinjee-tsc

security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/uaa/oauth/token #令牌端点
#      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize #授权端点
#      client-id: qinjee-zuul #OAuth2客户端ID
#      client-secret: secret #OAuth2客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123
  
eureka: 
  instance: 
    appname: ${spring.application.name}
    #以IP地址进行注册
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #表示eureka client发送心跳给server的频率
    lease-renewal-interval-in-seconds: 30
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，如果在这个时间段内没有收到下一次心跳，则将该 instance移除
    lease-expiration-duration-in-seconds: 90
  client:
    service-url: 
      defaultZone: http://qinjee:qinjee2019@192.168.99.100:8888/eureka/
