server:
  port: 5555

spring: 
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 0
    
zuul: 
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
#  sensitiveHeaders的默认值初始值是"Cookie", "Set-Cookie", "Authorization"这三项，不设置为空会导致无法设置cookie
  sensitive-headers: 
  prefix: /api
  routes: 
    qinjee-tsc: 
      path: /tsc/**
      serviceId: qinjee-tsc

security:
  basic:
    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/uaa/oauth/token #令牌端点
#      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize #授权端点
#      client-id: qinjee-zuul #OAuth2客户端ID
#      client-secret: secret #OAuth2客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123
  
eureka: 
  instance:
    instance-id: qinjee-zuul-${server.port}
    appname: ${spring.application.name}
  client:
    service-url: 
      defaultZone: http://qinjee:qinjee2019@localhost:8888/eureka/
