server:
  port: 8088

eureka: 
  client:
    register-with-eureka: false #客户端不注册到eureka，只是进行服务的调用
    service-url:
      defaultZone: http://qinjee:qinjee2019@localhost:8888/eureka/
#      defaultZone: http://${security.user.name}:${security.user.password}@localhost:8888/eureka/,http://${security.user.name}:${security.user.password}@localhost:8889/eureka/