spring: 
  profiles: test
  
  datasource: 
    url: jdbc:mysql://localhost:3306/qinjee_ehr?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: qinjee2019
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: qinjee
    password: 123456
    publisher-confirms: false    #消息发送到交换机确认机制,是否确认回调
    
  #ElasticSearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
  
  #Redis
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 0

#注册中心指向start
eureka: 
  instance: 
    appname: ${spring.application.name}
    #以IP地址进行注册
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #表示eureka client发送心跳给server的频率
    lease-renewal-interval-in-seconds: 30
    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，如果在这个时间段内没有收到下一次心跳，则将该 instance移除
    lease-expiration-duration-in-seconds: 90
  client:
    service-url: 
      defaultZone: http://qinjee:qinjee2019@192.168.99.100:8888/eureka/

server: 
  port: 8080
  
logging: 
  config: classpath:log4j/log4j2_test.xml