#默认使用配置
spring: 
  application: 
    name: qinjee-tsc
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
